### ISSUE TITLE
Try new API Documenter feature

### ISSUE THREAD

**Issue by octogonz** [faastjs/faast.js#374]
@acchou FYI we just released an API Documenter update that adds hyperlinks for types in function parameters and return values.  (See https://github.com/microsoft/rushstack/issues/1611 for details.) Could you give it a try and confirm that it works correctly with Docusaurus?

**Comment by acchou** [comment]
It largely works; see https://faastjs.org/docs/api/faastjs.faast for an example page. I noticed some artifacts, such as this page: https://faastjs.org/docs/api/faastjs.commonoptions, where tables are now mis-formatted. I'll take a closer look.

**Comment by acchou** [comment]
It looks like the cause of the table misformatting is the markdown used to be:

```
|  [gc](./faastjs.commonoptions.gc.md) | <code>&quot;auto&quot; &#124; &quot;force&quot; &#124; &quot;off&quot;</code> | Garbage collector mode. Default: <code>&quot;auto&quot;</code>. |
```

And is now:

```
|  [gc](./faastjs.commonoptions.gc.md) | "auto" \| "force" \| "off" | Garbage collector mode. Default: <code>&quot;auto&quot;</code>. |
```

That said, it renders correctly on GitHub: https://github.com/faastjs/faast.js/blob/master/docs/api/faastjs.commonoptions.md

The problem appears that `\|` isn't supported by docusaurus' markdown renderer as an escape for the table column separator. I'll dig a little further.

**Comment by acchou** [comment]
See https://github.com/facebook/docusaurus/issues/2004

**Comment by acchou** [comment]
Would it be possible for api-documenter to escape `|` as `&#124;` instead of `\|`?

**Comment by acchou** [comment]
Overall the feature appears to work well. Many types are now linked, which makes navigating the documentation much more convenient, and it also makes it less burdensome for me as a developer because I don't need to add as many type references to the documentation manually.

Some specific feedback on areas which might be improved:

(1) When an interface extends another interface, it would be useful to have a link to the latter. For example, on this page: https://faastjs.org/docs/api/faastjs.awsoptions it would be nice to have a generated link to `CommonOptions` (I had to add the link that's there manually).

(2) Perhaps more controversially, adding a link "downwards" to extending interfaces. For example on this page: https://faastjs.org/docs/api/faastjs.commonoptions it would be convenient to see links to `AwsOptions`, `GoogleOptions`, and `LocalOptions` automatically generated.

But again, overall this is great!

**Comment by octogonz** [comment]
@acchou  good suggestions!  Sorry it took me some time to follow up.

> (1) When an interface extends another interface, it would be useful to have a link to the latter. For example, on this page: https://faastjs.org/docs/api/faastjs.awsoptions it would be nice to have a generated link to `CommonOptions` (I had to add the link that's there manually).

This is very easy to implement. The information is already in the .api.json file because the DocFX target already supports it. We just need to wire it up.

> (2) Perhaps more controversially, adding a link "downwards" to extending interfaces. For example on this page: https://faastjs.org/docs/api/faastjs.commonoptions it would be convenient to see links to `AwsOptions`, `GoogleOptions`, and `LocalOptions` automatically generated.

This is also doable, but it needs to be computed as a post-process by API Documenter, because the set of downwards links depends on the set of .api.json files being processed together.  The hyperlinking information is already available in the .api.json file.  So the computation would essentially involve scanning all the uplinks and remembering which hyperlinks could be resolved, so we can write those as downlinks during generation. A little more involved, but nothing challenging.

There might already be GitHub issues for these; I can't remember.  But we should try to get it fixed. It would be really nice!
