### ISSUE TITLE
Support Date, Buffer, and other common classes as arguments and return values

### ISSUE THREAD

**Issue by acchou** [faastjs/faast.js#43]
We currently use `JSON.stringify()` and `JSON.parse()` to serialize arguments and return values. These don't support common objects like Date and Buffer, among others. We should either change to a library that does support more of these built-in classes, or add custom support for them.

**Comment by microsoftly** [comment]
How do you feel about adding an option that allows for loss of data instead of throwing a `FaastError` (re: https://github.com/faastjs/faast.js/commit/56da0c08c18b7f1e5e1ca912be5a11ef4de62fc3#diff-475be03cf7abc7779d998f1e481fe3b4R31).

My case involves returning an object that sometimes has values that are not serializable, but I know that they are not needed. To get around it, I'm adding in a `return JSON.parse(JSON.stringify(result))` to my faast fn to avoid this.

**Comment by acchou** [comment]
You can set the option `validateSerialization: false`: https://faastjs.org/docs/api/faastjs.commonoptions.validateserialization
