### ISSUE TITLE
Support Node.js 18.x runtime of AWS Lambda by upgrading to AWS SDK v3

### ISSUE THREAD

**Issue by irico3** [faastjs/faast.js#982]
At the end of last year, [Node.js 18.x runtime became available in AWS Lambda](https://aws.amazon.com/jp/blogs/compute/node-js-18-x-runtime-now-available-in-aws-lambda/). It bundles AWS SDK for JavaScript v3 instead of v2.

faast.js does not work on Node.js 18.x runtimes. It can not find AWS SDK v2, because it is not bundled by webpack setting.

https://faastjs.org/docs/api/faastjs.commonoptions.webpackoptions
> Default:
> - aws: { externals: [new RegExp("^aws-sdk/?")] }. In the lambda environment "aws-sdk" is available in the ambient environment and does not need to be bundled.

My team is eager to use Node.js 18.x runtime with faast.js.
Is there any plan to support AWS SDK v3 in the future schedule?

**Comment by acchou** [comment]
I've added support for node18 by allowing webpack to package aws-sdk. Take a look at https://github.com/faastjs/faast.js/blob/942bfae2743c446d61f9ccccaf86a337a2fad699/test/aws-other.test.ts#L34

The options you need to enable this are:
(1) `awsLambdaOptions: { Runtime: "nodejs18.x" }`
(2) A new option `webpackAwsSdk: true`

The first option selects the node18 runtime. The second option causes webpack to bundle aws-sdk v2 instead of using the external version available on the Lambda itself. Note that aws-sdk is somewhat large so this may reduce the code size you can bundle with faast.js. This can be mitigated by using the `packageJson` option to create a lambda layer automatically.

Out of curiosity, how are you using faast.js?

**Comment by irico3** [comment]
@acchou 
Thank you for your prompt work!
It is used for the build process of a repository called cybozu/duck.
It's always a great help. 
https://github.com/cybozu/duck
